[package]
name = "image-fetch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet = { path = "../../sdk/rust/inferlet" }
image = "0.25.5"

[profile.release]
lto = true
