[package]
name = "tree-of-thought"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet = { path = "../../sdk/rust/inferlet" }
futures = "0.3"

[profile.release]
lto = true
