[package]
name = "es-rollout"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet = { path = "../../../../rust/inferlet" }
inferlet-macros = { path = "../../../../rust/inferlet-macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"