[package]
name = "es-update"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet = { path = "../../../../rust/inferlet" }
inferlet-macros = { path = "../../../../rust/inferlet-macros" }